[package]
name = "desktop-linux"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]
name = "desktop_linux"

[[bin]]
name = "desktop-linux-test"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true
log4rs.workspace = true
desktop-common = { path = "../desktop-common" }
smithay-client-toolkit = "0.19.2"
ashpd = { version = "0.11.0", default-features = false, features = ["async-std"] }
async-std = "1.13.1"

[build-dependencies]
cbindgen.workspace = true
