/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */
import org.gradle.internal.impldep.kotlinx.serialization.Serializable
import org.jetbrains.desktop.buildscripts.Arch
import org.jetbrains.desktop.buildscripts.CompileRustTask
import org.jetbrains.desktop.buildscripts.DownloadJExtractTask
import org.jetbrains.desktop.buildscripts.GenerateJavaBindingsTask
import org.jetbrains.desktop.buildscripts.KotlinDesktopToolkitAttributes
import org.jetbrains.desktop.buildscripts.KotlingDesktopToolkitArtifactType
import org.jetbrains.desktop.buildscripts.KotlingDesktopToolkitNativeProfile
import org.jetbrains.desktop.buildscripts.Os
import org.jetbrains.desktop.buildscripts.Platform
import org.jetbrains.desktop.buildscripts.buildPlatformRustTarget
import org.jetbrains.desktop.buildscripts.currentPlatform

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.ktlint)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
}

group = "org.jetbrains"
version = (project.properties["version"] as? String)?.takeIf { it.isNotBlank() && it != "unspecified" } ?: "SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.compileJava {
    options.compilerArgs = listOf("--enable-preview")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

tasks.test {
    val buildNativeTask = compileMacOSDesktopToolkitTaskByTarget[RustTarget(currentPlatform(), "dev")]!!
    dependsOn(buildNativeTask)
    // Use JUnit Platform for unit tests.
    jvmArgs("--enable-preview")
    val libFolder = buildNativeTask.flatMap { it.libraryFile }.map { it.parent }
    val logFile = layout.buildDirectory.file("test-logs/desktop_native.log")
    jvmArgumentProviders.add(
        CommandLineArgumentProvider {
            listOf(
                "-Dkdt.library.folder.path=${libFolder.get()}",
                "-Dkdt.debug=true",
                "-Dkdt.native.log.path=${logFile.get().asFile.absolutePath}",
            )
        },
    )
    useJUnitPlatform()
}

@Serializable
data class RustTarget(
    @get:Input val platform: Platform,
    @get:Input val profile: String,
)

// to install toolchain
// rustup target add --toolchain 1.85.0 x86_64-apple-darwin
val compileMacOSDesktopToolkitTaskByTarget = listOf(
    RustTarget(Platform(Os.MACOS, Arch.x86_64), "dev"),
    RustTarget(Platform(Os.MACOS, Arch.aarch64), "dev"),
    RustTarget(Platform(Os.MACOS, Arch.x86_64), "release"),
    RustTarget(Platform(Os.MACOS, Arch.aarch64), "release"),
).associateWith { target ->
    val platform = target.platform
    tasks.register<CompileRustTask>("compileNative-${buildPlatformRustTarget(platform)}-${target.profile}") {
        crateName = "desktop-macos"
        rustProfile = target.profile
        rustTarget = platform
        workspaceRoot = layout.projectDirectory.dir("../native")
        enabled = true
    }
}

val cargoFmtCheckTask = tasks.register<Exec>("cargoFmtCheck") {
    workingDir = layout.projectDirectory.dir("../native").getAsFile()
    commandLine("cargo", "fmt", "--check")
}

val cargoFmtTask = tasks.register<Exec>("cargoFmt") {
    workingDir = layout.projectDirectory.dir("../native").getAsFile()
    commandLine("cargo", "fmt")
}

val clippyCheckTask = tasks.register<Exec>("clippyCheck") {
    workingDir = layout.projectDirectory.dir("../native").getAsFile()
    commandLine("cargo", "clippy", "--workspace", "--all-targets", "--all-features", "--", "--deny", "warnings")
}

val clippyFixTask = tasks.register<Exec>("clippyFix") {
    workingDir = layout.projectDirectory.dir("../native").getAsFile()
    commandLine("cargo", "clippy", "--workspace", "--all-targets", "--all-features", "--fix", "--allow-dirty", "--allow-staged")
}

task("lint") {
    dependsOn(tasks.named("ktlintCheck"))
    dependsOn(clippyCheckTask)
    dependsOn(cargoFmtCheckTask)
}

task("autofix") {
    dependsOn(tasks.named("ktlintFormat"))
    dependsOn(clippyFixTask)
    dependsOn(cargoFmtTask)
}

val downloadJExtractTask = tasks.register<DownloadJExtractTask>("downloadJExtract") {
    slug = "22/6/openjdk-22-jextract+6-47"
    jextractDirectory = layout.buildDirectory.dir("jextract")
}

val nativeConsumable = configurations.consumable("nativeParts") {
    attributes {
        attribute(KotlinDesktopToolkitAttributes.TYPE, KotlingDesktopToolkitArtifactType.NATIVE_LIBRARY)
        attribute(KotlinDesktopToolkitAttributes.PROFILE, KotlingDesktopToolkitNativeProfile.DEBUG)
    }
}

compileMacOSDesktopToolkitTaskByTarget[RustTarget(currentPlatform(), "dev")]?.let { buildNativeTask ->
    artifacts.add(nativeConsumable.name, buildNativeTask.flatMap { it.libraryFile }) {
        builtBy(buildNativeTask) // redundant because of the flatMap usage above, but if you want to be sure you can specify that
    }
}

val generateBindingsTask = tasks.register<GenerateJavaBindingsTask>("generateBindings") {
    val buildNativeTask = compileMacOSDesktopToolkitTaskByTarget[RustTarget(currentPlatform(), "dev")]!!
    dependsOn(downloadJExtractTask)
    dependsOn(buildNativeTask)

    jextractBinary = downloadJExtractTask.flatMap { it.jextractBinary }
    headerFile = buildNativeTask.flatMap { it.headerFile }
    packageName = "org.jetbrains.desktop.macos.generated"
    generatedSourcesDirectory = layout.buildDirectory.dir("generated/sources/jextract/main/java/")
}

tasks.compileKotlin {
    dependsOn(generateBindingsTask)
}

tasks.compileJava {
    dependsOn(generateBindingsTask)
}

tasks.named<Jar>("sourcesJar") {
    dependsOn(generateBindingsTask)
}

val generateNativeResources = tasks.register<Sync>("generateResourcesDir") {
    destinationDir = layout.buildDirectory.dir("native").get().asFile

    compileMacOSDesktopToolkitTaskByTarget.forEach { (platform, task) ->
        from(task.map { it.libraryFile }) {
            into("")
        }
    }
}

// TODO: decide if this is needed, depending on how we package the native code
sourceSets.main {
    java.srcDirs(generateBindingsTask.flatMap { it.generatedSourcesDirectory })
    resources.srcDirs(generateNativeResources.map { it.destinationDir })
}

tasks.processResources {
    dependsOn(compileMacOSDesktopToolkitTaskByTarget[RustTarget(currentPlatform(), "dev")])
}

kotlin {
    explicitApi()
}

val spaceUsername: String? by project
val spacePassword: String? by project
publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            pom {
                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
            }
        }
    }
    repositories {
        maven {
            name = "IntellijDependencies"
            url = uri("https://packages.jetbrains.team/maven/p/ij/intellij-dependencies")
            credentials {
                username = spaceUsername
                password = spacePassword
            }
        }
    }
}
