pluginManagement {
    plugins {
        kotlin("jvm") version "2.3.21"
    }
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
    id("org.jlleitschuh.gradle.ktlint") version "14.2.0" apply false
    id("org.jetbrains.kotlin.jvm") version "2.3.21" apply false
    // The Compose compiler plugin ships with Kotlin, so this version tracks the Kotlin version above.
    id("org.jetbrains.kotlin.plugin.compose") version "2.3.21" apply false
}

rootProject.name = "kotlin-desktop-toolkit"

include("kotlin-desktop-toolkit")
include("sample")
