/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */
import org.gradle.internal.impldep.kotlinx.serialization.Serializable
import org.jetbrains.desktop.buildscripts.Arch
import org.jetbrains.desktop.buildscripts.CargoFmtTask
import org.jetbrains.desktop.buildscripts.ClippyTask
import org.jetbrains.desktop.buildscripts.CompileRustTask
import org.jetbrains.desktop.buildscripts.CrossCompilationSettings
import org.jetbrains.desktop.buildscripts.DownloadJExtractTask
import org.jetbrains.desktop.buildscripts.GenerateJavaBindingsTask
import org.jetbrains.desktop.buildscripts.KotlinDesktopToolkitAttributes
import org.jetbrains.desktop.buildscripts.KotlingDesktopToolkitArtifactType
import org.jetbrains.desktop.buildscripts.KotlingDesktopToolkitNativeProfile
import org.jetbrains.desktop.buildscripts.Os
import org.jetbrains.desktop.buildscripts.Platform
import org.jetbrains.desktop.buildscripts.buildPlatformRustTarget
import org.jetbrains.desktop.buildscripts.getWorkspaceHeaderFile
import org.jetbrains.desktop.buildscripts.hostArch
import org.jetbrains.desktop.buildscripts.targetArch

private val crossCompilation = CrossCompilationSettings.create(project)
private val defaultTargetPlatform = Platform(Os.LINUX, targetArch(project) ?: hostArch())
private val nativeDir = layout.projectDirectory.dir("../native")
private val rustCrateName = "desktop-linux"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.ktlint)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
}

group = "org.jetbrains"
version = (project.properties["version"] as? String)?.takeIf { it.isNotBlank() && it != "unspecified" } ?: "SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.compileJava {
    options.compilerArgs = listOf("--enable-preview")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

@Serializable
data class RustTarget(
    @get:Input val platform: Platform,
    @get:Input val profile: String,
)

val enabledPlatforms = listOf(Platform(Os.LINUX, Arch.x86_64), Platform(Os.LINUX, Arch.aarch64)).filter { crossCompilation.enabled(it) }
val profiles = listOf("dev")

val compileLinuxDesktopToolkitTaskByTarget = buildMap {
    for (platform in enabledPlatforms) {
        for (profile in profiles) {
            val buildNativeTask = tasks.register<CompileRustTask>("compileNative-${buildPlatformRustTarget(platform)}-$profile") {
                crateName = rustCrateName
                rustProfile = profile
                rustTarget = platform
                workspaceRoot = nativeDir
                enabled = true
            }
            put(RustTarget(platform, profile), buildNativeTask)
        }
    }
}

// Only run tests if there is a Wayland composer available
System.getenv("WAYLAND_DISPLAY")?.let { _ ->
    compileLinuxDesktopToolkitTaskByTarget[RustTarget(defaultTargetPlatform, "dev")]?.let { buildNativeTask ->
        tasks.test {
            // Use JUnit Platform for unit tests.
            jvmArgs("--enable-preview")
            val logFile = layout.buildDirectory.file("test-logs/desktop_native.log")
            dependsOn(buildNativeTask)
            val libFolder = buildNativeTask.flatMap { it.libraryFile }.map { it.parent }
            jvmArgumentProviders.add(
                CommandLineArgumentProvider {
                    listOf(
                        "-Dkdt.library.folder.path=${libFolder.get()}",
                        "-Dkdt.debug=true",
                        "-Dkdt.native.log.path=${logFile.get().asFile.absolutePath}",
                    )
                },
            )
            useJUnitPlatform()
        }
    }
}

val cargoFmtCheckTask = tasks.register<CargoFmtTask>("cargoFmtCheck") {
    checkOnly = true
    workingDir = nativeDir.asFile
}

val cargoFmtTask = tasks.register<CargoFmtTask>("cargoFmt") {
    workingDir = nativeDir.asFile
    mustRunAfter(clippyFixTask)
}

val clippyCheckTasks = enabledPlatforms.map { platform ->
    val rustTarget = buildPlatformRustTarget(platform)
    tasks.register<ClippyTask>("clippyCheck-$rustTarget") {
        checkOnly = true
        workingDir = nativeDir.asFile
        targetPlatform = platform
        crateName = rustCrateName
    }
}

val clippyFixTask = tasks.register<ClippyTask>("clippyFix") {
    workingDir = nativeDir.asFile
    targetPlatform = defaultTargetPlatform
    crateName = rustCrateName
}

task("lint") {
    dependsOn(tasks.named("ktlintCheck"))
    dependsOn(clippyCheckTasks)
    dependsOn(cargoFmtCheckTask)
}

task("autofix") {
    dependsOn(tasks.named("ktlintFormat"))
    dependsOn(clippyFixTask)
    dependsOn(cargoFmtTask)
}

val downloadJExtractTask = tasks.register<DownloadJExtractTask>("downloadJExtract") {
    slug = "22/6/openjdk-22-jextract+6-47"
    jextractDirectory = layout.buildDirectory.dir("jextract")
}

val nativeConsumable = configurations.consumable("linuxNativeParts") {
    attributes {
        attribute(KotlinDesktopToolkitAttributes.TYPE, KotlingDesktopToolkitArtifactType.NATIVE_LIBRARY)
        attribute(KotlinDesktopToolkitAttributes.PROFILE, KotlingDesktopToolkitNativeProfile.DEBUG)
    }
}

compileLinuxDesktopToolkitTaskByTarget[RustTarget(defaultTargetPlatform, "dev")]?.let { buildNativeTask ->
    artifacts.add(nativeConsumable.name, buildNativeTask.flatMap { it.libraryFile }) {
        builtBy(buildNativeTask) // redundant because of the flatMap usage above, but if you want to be sure you can specify that
    }
}

val generateBindingsTask = tasks.register<GenerateJavaBindingsTask>("generateBindings") {
    val buildNativeTask = compileLinuxDesktopToolkitTaskByTarget[RustTarget(defaultTargetPlatform, "dev")]
    dependsOn(downloadJExtractTask)
    headerFile = if (buildNativeTask != null) {
        dependsOn(buildNativeTask)
        buildNativeTask.flatMap { it.headerFile }
    } else {
        project.provider { getWorkspaceHeaderFile(nativeDir, rustCrateName) }
    }

    jextractBinary = downloadJExtractTask.flatMap { it.jextractBinary }
    packageName = "org.jetbrains.desktop.linux.generated"
    generatedSourcesDirectory = layout.buildDirectory.dir("generated/sources/jextract/main/java/")
}

tasks.compileKotlin {
    dependsOn(generateBindingsTask)
}

tasks.compileJava {
    dependsOn(generateBindingsTask)
}

tasks.named<Jar>("sourcesJar") {
    dependsOn(generateBindingsTask)
}

val generateNativeResources = tasks.register<Sync>("generateResourcesDir") {
    destinationDir = layout.buildDirectory.dir("native").get().asFile

    compileLinuxDesktopToolkitTaskByTarget.values.forEach { task ->
        from(task.map { it.libraryFile }) {
            into("")
        }
    }
}

// TODO: decide if this is needed, depending on how we package the native code
sourceSets.main {
    java.srcDirs(generateBindingsTask.flatMap { it.generatedSourcesDirectory })
    resources.srcDirs(generateNativeResources.map { it.destinationDir })
}

tasks.processResources {
    compileLinuxDesktopToolkitTaskByTarget[RustTarget(defaultTargetPlatform, "dev")]?.let {
        dependsOn(it)
    }
}

kotlin {
    explicitApi()
}

val spaceUsername: String? by project
val spacePassword: String? by project
publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            pom {
                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
            }
        }
    }
    repositories {
        maven {
            name = "IntellijDependencies"
            url = uri("https://packages.jetbrains.team/maven/p/ij/intellij-dependencies")
            credentials {
                username = spaceUsername
                password = spacePassword
            }
        }
    }
}
