language = "C"
header = "/* This header is generated please don't edit it manually. */"

[macro_expansion]
# Whether bindings should be generated for instances of the bitflags! macro.
# default: false
bitflags = true

[parse]
## Whether to parse dependent crates and include their types in the output
## default: false
#parse_deps = false
#include = ["kwm-macos"]
clean = true

[parse.expand]
# A list of crate names that should be run through `cargo expand` before
# parsing to expand any macros. Note that if a crate is named here, it
# will always be parsed, even if the blacklist/whitelist says it shouldn't be.
#
# default: []
crates = ["kwm-macos"]