/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jetbrains.kwm.tests

import org.jetbrains.kwm.Library
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(1, 2) == 3, "someLibraryMethod should return 'true'")
    }
}
