/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jetbrains.kwm

import org.jetbrains.kwm.macos.generated.kwm_macos_h.add_numbers

class Library {

    init {
        println("Library path: ${System.getenv("DYLD_LIBRARY_PATH")}")
    }

    fun someLibraryMethod(a: Int, b: Int): Int {
        return add_numbers(a, b)
    }
}


