name: "Publish"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+.[0-9]+"

env:
  RUST_VERSION: 1.88.0 # the same as in rust-toolchain

jobs:
  publish_all:
    strategy:
      matrix:
        targets: [
          { os: "macos-14",
            rust_targets: "x86_64-apple-darwin,aarch64-apple-darwin",
            publish_common: false,
            package_manager: "brew" },
          { os: "ubuntu-22.04",
            rust_targets: "x86_64-unknown-linux-gnu",
            publish_common: false,
            package_manager: "apt" },
          { os: "ubuntu-22.04-arm",
            rust_targets: "aarch64-unknown-linux-gnu",
            publish_common: true,
            package_manager: "apt" },
          { os: "windows-2025",
            rust_targets: "x86_64-pc-windows-msvc",
            publish_common: false,
            package_manager: "winget" },
          { os: "windows-11-arm",
            rust_targets: "aarch64-pc-windows-msvc",
            publish_common: false,
            package_manager: "winget" }
        ]
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Dependencies
        if: "${{ matrix.targets.package_manager == 'apt' }}"
        run: |
          sudo apt update
          sudo apt install libwayland-dev libxkbcommon-dev

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: ${{ matrix.targets.rust_targets }}
          components: rustfmt, clippy
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: >
          ./gradlew :kotlin-desktop-toolkit:publish
          -PenableCrossCompileToMacosX86_64=${{ matrix.targets.os == 'macos-14' }}
          -PpublishCommon=${{ matrix.targets.publish_common }}
          -PspaceUsername=${{ secrets.SPACE_USERNAME }}
          -PspacePassword=${{ secrets.SPACE_PASSWORD }}
          -Pversion=${{ github.ref_name }}
